# Generated by Django 5.0.1 on 2025-10-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('short_description', models.CharField(max_length=300, verbose_name='Qisqa tavsif')),
                ('content', models.TextField(verbose_name='To‘liq matn')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Rasm')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='E’lon qilingan sana')),
                ('category', models.CharField(choices=[('exhibition', 'Ko‘rgazma'), ('production', 'Yangi ishlab chiqarish'), ('other', 'Boshqa yangilik')], default='other', max_length=100, verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
                'ordering': ['-published_date'],
            },
        ),
    ]
