# Generated by Django 5.0.1 on 2025-10-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('history', models.TextField(blank=True, null=True, verbose_name='Tarix')),
                ('technology', models.TextField(blank=True, null=True, verbose_name='Texnologiyalar')),
                ('projects', models.TextField(blank=True, null=True, verbose_name='Joriy loyihalar')),
                ('investors', models.TextField(blank=True, null=True, verbose_name='Investorlar uchun ma’lumot')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kompaniya haqida',
                'verbose_name_plural': 'Kompaniya haqida',
            },
        ),
    ]
