# Generated by Django 5.0.1 on 2025-10-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Mahsulot nomi')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('technical_specs', models.TextField(blank=True, null=True, verbose_name='Texnik xarakteristikalar')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Narx (so‘mda)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Rasm')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Qo‘shilgan sana')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
